# Generated by Django 3.0.8 on 2020-10-13 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rvl_blog', '0004_auto_20201013_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 16, 22, 2, 388177, tzinfo=utc)),
        ),
    ]
