# Generated by Django 3.0.8 on 2020-10-13 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rvl_blog', '0005_auto_20201013_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 16, 24, 37, 578034, tzinfo=utc)),
        ),
    ]
